name: Update Calendar

on:
  schedule:
    - cron: "10 7 * * 5"
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '>= 363.0.0'

      - name: Run the scraper and update calendar
        run: |
          python events.py  # Adjust command as needed
        env:
          EVENT_URL: ${{ secrets.EVENT_URL }}

      - name: Print scraper log
        run: |
          cat scraper_log.log
          
      - name: Upload file to GCS
        run: |
          gsutil cp Market.ics gs://market-calendar-bucket/

      - name: Set ACL for Market.ics
        run: |
          gsutil acl ch -u AllUsers:R gs://market-calendar-bucket/Market.ics

      - name: List Files in GCS Bucket
        run: |
          gsutil ls gs://market-calendar-bucket/

      - name: Upload Log File to GCS
        run: |
          gsutil cp scraper_log.log gs://market-calendar-bucket/
